---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  ports:
  - name: "cartservice"
    #port accessible inside the cluster..if two pods wants to communicate with each other
    port: 8082
    protocol: TCP
    #port to forward to inside the pod..
    targetPort: 8080
    #port accessible outside the cluster.
    #nodePort: 30001
  selector:
    app: cart-app
  #type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      name: cart-pod
      labels:
        app: cart-app
    spec:
      containers:
      - image: bhushapkhaire/com.ocsc.poc.cart
        name: cart-api
        ports: 
          - containerPort: 8080